# Generated by Django 4.2.18 on 2025-03-12 08:00

from django.db import migrations
from django.db.migrations.state import StateApps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from user.enums import USER_ROLE



def create_default_data(state: StateApps, schema: BaseDatabaseSchemaEditor):
    User = state.get_model('user', 'User')
    instance_list_list = [
        User(
            role=USER_ROLE.BOT,
            username='bot',
            is_active=False,
        ),
    ]
    User.objects.bulk_create(instance_list_list)



class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_data)
    ]
