# Generated by Django 4.2.18 on 2025-06-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20250312_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BOT', 'Bot'), ('USER', 'User'), ('SCHOOL_ADMIN', 'School Admin'), ('ANONYMOUS_USER', 'Anonymous User')], default='SCHOOL_ADMIN', max_length=255),
        ),
    ]
