# Generated by Django 4.2.18 on 2025-06-03 02:32

from django.db import migrations
from django.db.migrations.state import StateApps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor




def create_default_data(state: StateApps, schema: BaseDatabaseSchemaEditor):
    Model = state.get_model('user', 'Setting')
    instance_list_list = [
        Model(
            name='Waylearn',
            policy='',
            terms='',
        ),
    ]
    Model.objects.bulk_create(instance_list_list)



class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_setting'),
    ]

    operations = [
        migrations.RunPython(create_default_data)
    ]
