# Generated by Django 4.2.18 on 2025-06-03 08:58

from django.db import migrations
from django.db.migrations.state import StateApps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from user.enums import USER_ROLE




def create_default_data(state: StateApps, schema: BaseDatabaseSchemaEditor):
    UserModel = state.get_model('user', 'User')
    SchoolModel = state.get_model('user', 'School')
    school_admins = UserModel.objects.filter(
        role=USER_ROLE.SCHOOL_ADMIN
    )
    instance_list_list = []
    for user in school_admins:
        instance_list_list.append(SchoolModel(
            user=user,
            name='',
        ))
    SchoolModel.objects.bulk_create(instance_list_list)



class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_school'),
    ]

    operations = [
        migrations.RunPython(create_default_data)
    ]
