# Generated by Django 4.2.18 on 2025-06-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20250603_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Active'), (2, 'Inactive'), (3, 'Deleted')], default=1),
        ),
    ]
