# Generated by Django 4.2.18 on 2025-06-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0)),
                ('max_teacher', models.IntegerField(default=1)),
                ('unlimited_chat', models.BooleanField(default=False)),
                ('allow_book_full_access', models.BooleanField(default=False)),
                ('allow_book_200_image', models.BooleanField(default=False)),
                ('allow_book_soft_copy', models.BooleanField(default=False)),
                ('allow_book_hard_10p_off', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
