# Generated by Django 4.2.18 on 2025-06-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Active'), (2, 'Inactive'), (3, 'Deleted')], default=1),
        ),
        migrations.AddField(
            model_name='setting',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Active'), (2, 'Inactive'), (3, 'Deleted')], default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Active'), (2, 'Inactive'), (3, 'Deleted')], default=1),
        ),
    ]
