# Generated by Django 4.2.18 on 2025-06-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_school_status_setting_status_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BOT', 'Bot'), ('USER', 'User'), ('STUDENT', 'Student'), ('SCHOOL_ADMIN', 'School Admin'), ('TEACHER', 'Teacher'), ('ANONYMOUS_USER', 'Anonymous User')], default='SCHOOL_ADMIN', max_length=255),
        ),
    ]
