# Generated by Django 4.2.18 on 2025-08-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='per_user_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='yearly_price',
            field=models.FloatField(default=0),
        ),
    ]
