# Generated by Django 4.2.18 on 2025-08-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_subscription_per_user_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('BOT', 'Bot'), ('USER', 'User'), ('STUDENT', 'Student'), ('SCHOOL_ADMIN', 'School Admin'), ('TEACHER', 'Teacher'), ('ANONYMOUS_USER', 'Anonymous User')], default='SCHOOL_ADMIN', max_length=255),
        ),
    ]
