# Generated by Django 4.2.18 on 2025-08-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='yearly_price',
        ),
        migrations.AddField(
            model_name='setting',
            name='yearly_subscription_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='BASIC', max_length=255),
        ),
    ]
